### ISSUE TITLE
When the initialization of an element triggers a Model update, a NPE is thrown

### ISSUE THREAD

**Issue by amischler** [dooApp/FXForm2#101]
This happen in some rare cases where the adapter is not mapping perfectly "one to one", e.g. an Adapter adapting between a Date and a LocalDate.

java.lang.NullPointerException: null
	at com.dooapp.fxform.validation.ClassLevelValidator.getElementValidator(ClassLevelValidator.java:80) ~[core-8.0.8.jar:na]
	at com.dooapp.fxform.validation.ClassLevelValidator.validate(ClassLevelValidator.java:68) ~[core-8.0.8.jar:na]
	at com.dooapp.fxform.controller.PropertyEditorController$2.changed(PropertyEditorController.java:81) ~[core-8.0.8.jar:na]
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182) [jfxrt.jar:na]
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) [jfxrt.jar:na]
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105) [jfxrt.jar:na]
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112) [jfxrt.jar:na]
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:145) [jfxrt.jar:na]
	at javafx.beans.property.ObjectProperty.setValue(ObjectProperty.java:69) [jfxrt.jar:na]
	at com.dooapp.fxform.model.impl.PropertyFieldElement.setValue(PropertyFieldElement.java:38) [core-8.0.8.jar:na]
	at com.dooapp.fxform.controller.PropertyEditorController$1.changed(PropertyEditorController.java:67) [core-8.0.8.jar:na]
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361) [jfxrt.jar:na]
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) [jfxrt.jar:na]
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105) [jfxrt.jar:na]
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112) [jfxrt.jar:na]
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:145) [jfxrt.jar:na]
	at javafx.beans.property.ObjectProperty.setValue(ObjectProperty.java:69) [jfxrt.jar:na]
	at com.dooapp.fxform.controller.PropertyEditorController.updateView(PropertyEditorController.java:95) [core-8.0.8.jar:na]
	at com.dooapp.fxform.controller.PropertyEditorController.bind(PropertyEditorController.java:85) [core-8.0.8.jar:na]
	at com.dooapp.fxform.controller.NodeController$1.changed(NodeController.java:48) [core-8.0.8.jar:na]
	at com.dooapp.fxform.controller.NodeController$1.changed(NodeController.java:40) [core-8.0.8.jar:na]
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182) [jfxrt.jar:na]
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) [jfxrt.jar:na]
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105) [jfxrt.jar:na]
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112) [jfxrt.jar:na]
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:145) [jfxrt.jar:na]
	at com.dooapp.fxform.controller.NodeController.setNode(NodeController.java:71) [core-8.0.8.jar:na]
	at com.dooapp.fxform.controller.ElementController.updateSkin(ElementController.java:66) [core-8.0.8.jar:na]
	at com.dooapp.fxform.controller.PropertyElementController.updateSkin(PropertyElementController.java:111) [core-8.0.8.jar:na]
	at com.dooapp.fxform.controller.ElementController.<init>(ElementController.java:58) [core-8.0.8.jar:na]
	at com.dooapp.fxform.controller.PropertyElementController.<init>(PropertyElementController.java:38) [core-8.0.8.jar:na]
	at com.dooapp.fxform.AbstractFXForm.createPropertyElementController(AbstractFXForm.java:178) [core-8.0.8.jar:na]
	at com.dooapp.fxform.AbstractFXForm.configure(AbstractFXForm.java:169) [core-8.0.8.jar:na]
	at com.dooapp.fxform.AbstractFXForm$3.onChanged(AbstractFXForm.java:120) [core-8.0.8.jar:na]
	at com.sun.javafx.binding.ListExpressionHelper$SingleListChange.fireValueChangedEvent(ListExpressionHelper.java:299) [jfxrt.jar:na]
	at com.sun.javafx.binding.ListExpressionHelper.fireValueChangedEvent(ListExpressionHelper.java:108) [jfxrt.jar:na]
	at javafx.beans.property.ListPropertyBase.fireValueChangedEvent(ListPropertyBase.java:200) [jfxrt.jar:na]
	at javafx.beans.property.ListPropertyBase.lambda$new$30(ListPropertyBase.java:56) [jfxrt.jar:na]
	at javafx.beans.property.ListPropertyBase$$Lambda$284/1559067421.onChanged(Unknown Source) [jfxrt.jar:na]
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329) [jfxrt.jar:na]
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73) [jfxrt.jar:na]
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233) [jfxrt.jar:na]
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482) [jfxrt.jar:na]
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541) [jfxrt.jar:na]
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205) [jfxrt.jar:na]
	at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90) [jfxrt.jar:na]
	at javafx.beans.binding.ListExpression.setAll(ListExpression.java:370) [jfxrt.jar:na]
	at com.dooapp.fxform.AbstractFXForm$2.changed(AbstractFXForm.java:112) [core-8.0.8.jar:na]
	at com.dooapp.fxform.AbstractFXForm$2.changed(AbstractFXForm.java:109) [core-8.0.8.jar:na]
	at com.sun.javafx.binding.ListExpressionHelper$SingleChange.fireValueChangedEvent(ListExpressionHelper.java:232) [jfxrt.jar:na]
	at com.sun.javafx.binding.ListExpressionHelper.fireValueChangedEvent(ListExpressionHelper.java:102) [jfxrt.jar:na]
	at javafx.beans.property.ListPropertyBase.fireValueChangedEvent(ListPropertyBase.java:186) [jfxrt.jar:na]
	at javafx.beans.property.ListPropertyBase.markInvalid(ListPropertyBase.java:220) [jfxrt.jar:na]
	at javafx.beans.property.ListPropertyBase.bind(ListPropertyBase.java:278) [jfxrt.jar:na]
	at com.dooapp.fxform.FXForm$1.changed(FXForm.java:87) [core-8.0.8.jar:na]
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361) [jfxrt.jar:na]
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) [jfxrt.jar:na]
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105) [jfxrt.jar:na]
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112) [jfxrt.jar:na]
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:145) [jfxrt.jar:na]
	at com.dooapp.fxform.FXForm.setSource(FXForm.java:101) [core-8.0.8.jar:na]

**Comment by amischler** [comment]
Fixed in 8.0.9-SNAPSHOT

**Comment by amischler** [comment]
Fixed in 8.0.9
