### ISSUE TITLE
ArrayIndexOutOfBoundsException in ClassLevelValidator

### ISSUE THREAD

**Issue by amischler** [dooApp/FXForm2#151]
This issue appear randomly when running Issue150Test#test150 :
```
java.lang.ArrayIndexOutOfBoundsException: 11
	at com.sun.javafx.collections.ListListenerHelper$Generic.addListener(ListListenerHelper.java:270)
	at com.sun.javafx.collections.ListListenerHelper.addListener(ListListenerHelper.java:60)
	at javafx.collections.ObservableListBase.addListener(ObservableListBase.java:220)
	at javafx.collections.FXCollections$UnmodifiableObservableListImpl.<init>(FXCollections.java:931)
	at javafx.collections.FXCollections.unmodifiableObservableList(FXCollections.java:387)
	at com.dooapp.fxform.AbstractFXForm.getFilteredElements(AbstractFXForm.java:401)
	at com.dooapp.fxform.validation.ClassLevelValidator.validate(ClassLevelValidator.java:67)
	at com.dooapp.fxform.controller.PropertyEditorController$2.changed(PropertyEditorController.java:100)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.IntegerPropertyBase.fireValueChangedEvent(IntegerPropertyBase.java:106)
	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:147)
	at com.dooapp.fxform.issues.Issue150Test$TestBean.setAge(Issue150Test.java:87)
	at com.dooapp.fxform.issues.Issue150Test.lambda$test150$2(Issue150Test.java:115)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by amischler** [comment]
Deployed in 8.2.0-SNAPSHOT
